name: Run Node File
on : push
jobs:
    test:
        runs-on: ubuntu-latest
        container: node:14
        steps:
            
            - run : node --version
            - run : npm --version
            - uses : actions/checkout@v3
            - run : node index.js